"""update track parameters

Revision ID: 1684fd3f5d83
Revises: 67e8dfc4db40
Create Date: 2025-05-06 00:08:21.635246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1684fd3f5d83'
down_revision: Union[str, None] = '67e8dfc4db40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('spectrogram_base64', sa.String(), nullable=True))
    op.add_column('tracks', sa.Column('waveform_base64', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'waveform_base64')
    op.drop_column('tracks', 'spectrogram_base64')
    # ### end Alembic commands ###
