"""add_projects_and_generated_audio_tables

Revision ID: 1a978995e4cd
Revises: 3e6dfb1b0896
Create Date: 2025-07-17 21:03:32.354195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a978995e4cd'
down_revision: Union[str, None] = '3e6dfb1b0896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
