"""add_sample

Revision ID: 250ca95737bd
Revises: b300691d55c5
Create Date: 2025-07-12 01:09:43.312688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250ca95737bd'
down_revision: Union[str, None] = 'b300691d55c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('tempo_bpm', sa.Float(), nullable=True),
    sa.Column('key_signature', sa.String(length=10), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.Column('spectral_centroid', sa.Float(), nullable=True),
    sa.Column('spectral_rolloff', sa.Float(), nullable=True),
    sa.Column('zero_crossing_rate', sa.Float(), nullable=True),
    sa.Column('mfcc_features', sa.JSON(), nullable=True),
    sa.Column('rhythm_pattern', sa.JSON(), nullable=True),
    sa.Column('harmonic_content', sa.JSON(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('complexity', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('is_generated', sa.Integer(), nullable=True),
    sa.Column('source_samples', sa.JSON(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_id'), 'samples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samples_id'), table_name='samples')
    op.drop_table('samples')
    # ### end Alembic commands ###
