"""change naming conventions

Revision ID: 444acde3116b
Revises: 68cc59175b64
Create Date: 2025-05-29 20:39:04.171148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444acde3116b'
down_revision: Union[str, None] = '68cc59175b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('duration_sec', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('waveplot_base64', sa.String(), nullable=True))
    op.drop_column('tracks', 'duration')
    op.drop_column('tracks', 'waveform_base64')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('waveform_base64', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tracks', 'waveplot_base64')
    op.drop_column('tracks', 'duration_sec')
    # ### end Alembic commands ###
